---
abstract: 'Translate Japanese MotorcycleGang Language'
author:
  - 'yuichi tsunoda <yuichi.tsunoda@gmail.com>'
build_requires: {}
configure_requires:
  Module::Build: 0.40
dynamic_config: 1
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.120921'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Acme-MotorcycleGang
provides:
  Acme::MotorcycleGang:
    file: lib/Acme/MotorcycleGang.pm
    version: v0.0.1
requires:
  Test::More: 0
  version: 0
version: v0.0.1
